version: "3"
services:
    api:
        container_name: todo-api
        image: ezraamos/todo-api:${IMAGE_TAG}
        ports:
            - "8000:80"
        env_file:
            - .env
        volumes:
            - ./.env:/app/.env # ← Mounts secrets into container

