name: Deploy Todo API in Dev Environment

on:
  push:
    branches:
      - dev

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ezraamos/todo-api:${{ github.sha }}

      - name: Create .env file
        run: |
          cat <<EOF > .env
          IMAGE_TAG=${{ github.sha }}
          DB_CONNECTION=${{ vars.DB_CONNECTION }}
          DB_HOST=${{ vars.DB_HOST }}
          DB_DATABASE=${{ vars.DB_DATABASE }}
          DB_USERNAME=${{ vars.DB_USERNAME }}
          DB_PASSWORD=${{ vars.DB_PASSWORD }}
          EOF

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml,.env"
          target: "/var/www/todo/backend/"

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/todo/backend
            docker-compose down || true
            docker-compose up -d
            docker image prune -a -f
